postgres:
  storage:
    local: ./backups
  source:
    username: postgres
    password: postgres
    hostname: localhost
    port: 5432
    database: category
  target:
    username: postgres
    password: postgres
    hostname: localhost
    port: 5433
    database: category
  
